spring.jpa.database-platform=org.hibernate.dialect.MySQL8DBDialect
spring.datasource.url=jdbc:mysql://localhost:3306/db_blog?useUnicode=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=adminadmin
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none
